name: Format Python code with Black

on:
  pull_request:
    branches:
      - master
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write

jobs:
  format:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install black
        run: pip install black

      - name: Run black formatter
        run: black . # black --check --diff . to fail if format is not ok + show what to change

      - name: Commit and push changes if needed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "ci: format Python code with Black"
            git push
          else
            echo "No formatting changes to commit."
          fi
  
